import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "../components/common/footer"
import Header from "../components/common/header"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden`}>
        <Header />
        <div className="flex flex-col min-h-screen">
          <main className="flex-grow pt-8 pb-8 px-4"> {/* 여백 설정 */}
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
